export const SET_CHATLIST = "SET_CHATLIST";
export const SET_CURRENT_CHAT = "SET_CURRENT_CHAT";
export const SET_MESSAGES_LIST = "SET_MESSAGES_LIST";
export const SET_DELETED_CHAT = "SET_DELETED_CHAT";
export const REMOVE_DELETED_CHAT = "REMOVE_DELETED_CHAT";
